apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: dev
  name: nginx-deployment
spec: 
  replicas: 2
  selector: 
   matchLabels:
    app: nginx
  template:
    metadata: 
     labels: 
       app: nginx
    spec:
     containers:
      - name: nginx-deployment
        image: nginx  

     tolerations:     
      - key: "sai"  
        value: "devops"
        operator: "Equal"
        effect:  "NoSchedule"   



  
