apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: sai
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
     containers: 
      - name: my-nginx
        image: nginx:latest
        env:
         - name: my-username 
           valueFrom:
             secretKeyRef:
               name: my-secret
               key: username
         - name: my-password 
           valueFrom:
              secretKeyRef:
               name: my-secret
               key: password      


                      


