apiVersion: apps/v1

kind: Deployment

metadata: 
  name: nginx-deployment
  namespace: dev

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:  
      labels: 
         app: nginx
    spec: 
      containers: 
       - name: nginx-deployment  
         image: nginx 
         envFrom:
           - configMapRef: 
               name: my-config 
          


 